Adding more Germany stations for DB PST
trainline-eu/stations pull request #1220
Opened 2023-10-26 08:09 UTC by jbailey6

Source is locations list, provided by DB PST.

2023-10-26 09:57 UTC, matheussilvasantos approved these changes

2023-10-26 10:20 UTC, misdoro commented
Hi, have you checked if we already have identical stations named slightly differently?
Maybe by geo coordinates

2023-10-26 10:26 UTC, misdoro requested changes
Hi, have you checked by geocoordinates if we already have similar stations that do not have DB ID? For ex Flughafen Terminal A/B Düsseldorf seems to be similar to already existing `Düsseldorf Flughafen Terminal`

2023-10-31 11:23 UTC, misdoro approved these changes

2023-10-31 11:23 UTC, merged